config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "votes#about"
  get "/welcome" => "demos#index"

  resources :legislators

  resources :profiles do
    member do
      get :registed_data
      get :profile_issues_result # get :issues_result
      get :profile_legislators_ships # get :similar_legislators
    end  
  end  

  resources :issues do
    member do
      post :vote
      post :clear_vote
    end
  end

  post "issues/clear_all" => "issues#clear_all"

  resources :votes

  namespace :admin do
    resources :users
    resources :issues 
    resources :votes
    resources :categories
  end  

  post "admin/issues/clear_all" => "admin/issues#clear_all"

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :issues do# ApiV1::IssuesController
      member do
        post :vote
        post :clear_vote
        post :clear_all
      end  
    end

    post "/issue_vote" => "issues#vote"
    get "/issues/show" => "issues#show"
    post "/clear_vote" => "issues#clear_vote"
    post "/clear_all" => "issues#clear_all"

    resources :legislators

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :profiles do
      member do
        get :registed_data
        get :profile_issues_result # get :issues_result
        get :profile_legislators_ships # get :similar_legislators
      end  
    end

    patch "/profile_update" => "profile#update"

  end

  root :to => "issues#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base

    belongs_to :user

    belongs_to :location

   # has_many :profile_vote_ships
    #has_many :votting_votes, :through => :profile_vote_ships, :source => :vote

    has_many :profile_issue_ships
    has_many :votting_issues, :through => :profile_issue_ships, :source => :issue

    has_many :profile_legislator_ships
    has_many :legislators, :through => :profile_legislator_ships

    def admin?
      self.role == "admin"
    end

    def vote_issue?(issue)
      self.votting_issues.include?(issue)
    end
    
    def rebuild_profile_legislator_ships!  

      legislator_ids = Legislator.pluck(:id)
      categories = Category.pluck(:english_name) << "total"

      # get scores
      scores = Hash[ legislator_ids.map {|i| [i, Hash[categories.map{ |c| [c,0] }]] } ]

      my_issue_votes = Hash[ self.profile_issue_ships.pluck(:issue_id, :decision) ]
      my_issue_ids = my_issue_votes.keys

      votes = IssueVoteShip.includes(:issue => :category).where( :issue_id => my_issue_ids )
      vote_ids = votes.map{ |v| v.vote_id }
      vote_category_mapping = Hash[ votes.map{ |v| [v.vote_id, v.issue.category.english_name] } ]

      my_vote_decision = Hash[ votes.map{ |v| [v.vote_id,  my_issue_votes[v.issue_id]] } ]

      related_legislator_votes = LegislatorVoteShip.where( :vote_id => vote_ids )
      related_legislator_votes.each do |v|
        if v.decision.to_s == my_vote_decision[v.vote_id].to_s
          scores[ v.legislator_id ][ vote_category_mapping[v.vote_id] ] += 1
          scores[ v.legislator_id ][ "total" ] += 1
        end
      end

      # create profile_legislator_ships
      ActiveRecord::Base.transaction do    
        profile_legislator_ships.delete_all
        legislator_ids.each do |legislator_id|
          ship = self.profile_legislator_ships.new( :legislator_id => legislator_id, :profile_id =>  self.id)
          categories.each do |c|
            ship.public_send("#{c}=", scores[legislator_id][c] )
          end
          ship.save!
        end
      end
      
      ProfileLegislatorShip.where(:profile_id => nil).destroy_all

    end

    def update_votes_count!
      issue_ids = self.profile_issue_ships.pluck(:issue_id)      
      self.issue_number = issue_ids.size
      self.vote_number =  IssueVoteShip.where( :issue_id => issue_ids ).count
      self.save!      
    end

    def category_score_max(c)
      number = 0
      category_id = Category.where(:english_name => "#{c}").first.id
      
      issues = self.votting_issues.where(:category => category_id)
      issues.each do |i|
        number += i.votes.size
      end
      number  
    end


end

app/controllers/api_v1/profiles_controller.rb
class ApiV1::ProfilesController < ApiController

  before_action :authenticate_user_from_token!

  def update
    @profile = current_user.profile
    if authenticate_user_from_token!
      if profile_params
        @profile.update(profile_params)
        render :json => { :message => "auth_token OK",
                          :update => "update OK"}
      else
        render :json => { :message => "update fail"}
      end
    else                        
      render :json => { :message => "auth_token fail"}
    end

  end


  def profile_issues_result

    if authenticate_user_from_token!
      @profile = User.find_by_authentication_token( params[:auth_token] ).profile
      @issues = current_user.get_issues_report
    
    else
      render :json => { :message => "auth_token fail"}
    end
  end

  def profile_legislators_ships
    county = params[:county]
    legislator_number = params[:total_number]
    if authenticate_user_from_token!
      @profile = User.find_by_authentication_token( params[:auth_token] ).profile
      @similar_legislators = current_user.get_similar_legislators(legislator_number,county)
      @categories = Category.all

      @user_max_vote_number=0
      @categories.each do |c|
        @profile.category_score_max(c.english_name)
        if @profile.category_score_max(c.english_name) > @user_max_vote_number
          @user_max_vote_number = @profile.category_score_max(c.english_name)
        end
        
      end
  
    else
      render :json => { :message => "auth_token fail"}
    end
  end

  def registed_data
    if authenticate_user_from_token!
      @user = current_user
      @profile = current_user.profile
    else
      render :json => { :message => "auth_token fail"}
    end 
  end


  private

  def profile_params
    params.require(:profile).permit(:location_id, :username, :bio, :occupation)
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile

  def index
  end

  def show
  end

  def update
    if @profile.update(profile_params)
      flash[:notice] = "event was successfully updated"
      redirect_to profile_path(@profile)
    else
      render :back
    end
  end

  def profile_issues_result
    @issues = current_user.get_issues_report
  end

  def profile_legislators_ships
    county = params[:county]
    @similar_legislators = current_user.get_similar_legislators(10,county)
    @categories = Category.all

    @user_max_vote_number=0
    @categories.each do |c|
      @profile.category_score_max(c.english_name)
      if @profile.category_score_max(c.english_name) > @user_max_vote_number
        @user_max_vote_number = @profile.category_score_max(c.english_name)
      end
      
    end

  end

  def registed_data
    @profile = current_user.profile
  end

  private

  def profile_params
    params.require(:profile).permit(:location_id, :username, :bio, :occupation, :vote_number )
  end

  def set_profile
    @profile = current_user.profile
  end

end

app/helpers/api_v1/profiles_helper.rb
module ApiV1::ProfilesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def profile_issue_decision(profile_id, issue_id)
    ProfileIssueShip.where("profile_id = ? AND issue_id = ?" , profile_id,issue_id ).first.decision
  end

end

app/views/profiles/profile_issues_result.html.erb
<h1> profile_issues_result </h1>

<h2>我已經投過的議題：<%= @profile.issue_number%></h2>
<h2>相關法案數：<%= @profile.vote_number%></h2>

<table class="table">
  <tr>
    <td>議題名稱</td>
    <td>議題分類</td> 
    <td>個人投票</td>
    <td>所有投票結果</td>

  </tr>

  <% @issues.each do |i| %> 
  <tr>
    <td><%= link_to i[:issue].name, issue_path(i[:issue]) %></td>
    <td><%= i[:category] %></td>
    <td><%= i[:decision] %></td>
    <td>
    贊成：<%= i[:total_yes] %>
    反對：<%= i[:total_no] %>
    </td>
  </tr>
  <% end %>


</table>

<%= link_to "想審更多法案嗎？", issues_path, :class => "btn btn-default"%>

app/views/profiles/profile_legislators_ships.html.erb
<h1>你跟立委的相似度</h1>

<table class="table">
  <tr>
    <td>立委</td>
    <td>相似程度</td>
    <td>類型細節： 立委相同意見 ｜ 我的投票數 </td>
  </tr>

    <% @similar_legislators.each do |le|%>
      <tr>
        <td><%= le[:legislator].name %> </td>
        <td>  <%= le[:score] %>%</td>
        <td>
          <% @categories.each do |c| %>
            <li>
            <%= c.name %> ：
            <%= le[:legislator].profile_legislator_ships.first.get_score(c.english_name) %> | 
            <%= @profile.category_score_max(c.english_name) %></li>
          <%end%>
        </td>
      </tr>
    <% end %>


  


</table>
  

app/views/profiles/registed_data.html.erb
<%= form_for @profile, :url => profile_path(@profile), :method => :patch do |f|%>

<table class="table">

    <tr> 
      <td>   
        <div class="form-group">
          <%= f.label :username, "名稱" %>
          <%= f.text_field :username, :class => "form-control" %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="form-group">
          <%= f.label :bio, "性別" %>
          <%= f.select :bio,[["男","男"],["女","女"]] %>
        </div>
      </td>
    </tr>
    <tr>
    
    <tr>
      <td>
        <div class="form-group">
          <%= f.label :occupation, "職業" %>
          <%= f.text_field :occupation, :class => "form-control" %>
        </div>
      </td>
    </tr>
    
    <tr>
      <td>
        <div class="form-group">
          <%= f.label :location_id, "地區" %>
          <%= f.select :location_id, Location.all.map{|l| [l.name, l.id]}, :class => "form-control" %>
        </div>
      </td>
    </tr>

</table>

    <%= f.submit "送出",:class => "btn btn-primary" %>

<% end %>

app/views/profiles/show.html.erb
<div class="container">
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <h1><%= link_to "我的註冊資料", registed_data_profile_path(@profile) ,:class => "btn btn-primary btn-lg"%></h1>
  </div>
  <div class="col-md-2">
    <h1><%= link_to "我的投票結果", profile_issues_result_profile_path(@profile), :class => "btn btn-success btn-lg" %></h1>
  </div>
  <div class="col-md-2">
    <h1><%= link_to "我的立委相似度",profile_legislators_ships_profile_path(@profile),:class => "btn btn-danger btn-lg"  %></h1>
  </div>
  <div class="col-md-2">
    <h1><%= link_to "想審更多法案嗎？", issues_path, :class => "btn btn-default btn-lg"%></h1>
  </div>
  <div class="col-md-2"></div>

</div>



 