config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "votes#about"
  get "/welcome" => "demos#index"

  resources :legislators

  resources :profiles do
    member do
      get :registed_data
      get :profile_issues_result # get :issues_result
      get :profile_legislators_ships # get :similar_legislators
    end  
  end  

  resources :issues do
    member do
      post :vote
      post :clear_vote
    end
  end

  post "issues/clear_all" => "issues#clear_all"

  resources :votes

  namespace :admin do
    resources :users
    resources :issues 
    resources :votes
    resources :categories
  end  

  post "admin/issues/clear_all" => "admin/issues#clear_all"

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :issues do# ApiV1::IssuesController
      member do
        post :vote
        post :clear_vote
        post :clear_all
      end  
    end

    post "/issue_vote" => "issues#vote"
    get "/issues/show" => "issues#show"
    post "/clear_vote" => "issues#clear_vote"
    post "/clear_all" => "issues#clear_all"

    resources :legislators

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :profiles do
      member do
        get :registed_data
        get :profile_issues_result # get :issues_result
        get :profile_legislators_ships # get :similar_legislators
      end  
    end

    patch "/profile_update" => "profile#update"

  end

  root :to => "issues#index"

end

app/models/issue.rb
class Issue < ActiveRecord::Base
    validates_presence_of :name, :content

    belongs_to :category

    belongs_to :user

    has_many :issue_vote_ships
    has_many :votes, :through => :issue_vote_ships

    has_many :profile_issue_ships
    has_many :votting_profiles, :through => :profile_issue_ships, :source => :profile

    has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

    def vote_list
      self.votes.map{ |v| v.uid }
    end

    def vote_list=(str)
      arr = str.split(",")

      self.votes = arr.map do |v|
        vote = Vote.find_by_uid(v)
        vote
      end
    end


end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < ApplicationController

  #後台登入
  before_action :authenticate_user! 

  #檢查權限
  before_action :check_admin

  layout "admin"

  def index
    @issues = Issue.all

    if params[:issue_id]
      @issue = Issue.find( params[:issue_id] )
    else
      @issue = Issue.new
    end

  end

  def show
    @issue = Issue.find(params[:id])
  end


  def create
    @issue = Issue.new(issue_params)
    @issue.user = current_user

    if @issue.save
      flash[:notice] = "Create Success!"
      redirect_to admin_issues_path
    else
      flash[:alert] = "Create fail!"
      render admin_issues_path
    end

  end

  def update
    Issue.find(params[:id]).update(issue_params)

    if params[:issue][:vote_list]
      vote_list = params[:issue][:vote_list]
      vote_list.shift(1)

      vote_list.each do|v|
        vote_id = v.to_i
        IssueVoteShip.create( :issue_id => params[:id], :vote_id => vote_id)
      end
    end

    if params[:destroy_logo] == "1"

      @issue.logo = nil
    end

    flash[:notice] = "Update Success!"
    redirect_to admin_issue_path(params[:id])  
  end

  def destroy
    if params[:vote]
      issue_vote = IssueVoteShip.where(:issue_id => params[:id]).find_by_vote_id(params[:vote])
      issue_vote.destroy
      issue_vote.save
    end

    if params[:delete] == "issue"
      issue = Issue.find(params[:id])
      issue.delete
      issue.save!
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js # destroy.js.erb
    end
  end

  def clear_all
    @profile = Profile.find(params[:profile_id])

    @profile.profile_legislator_ships.delete_all
    @profile.profile_issue_ships.delete_all

    @profile.vote_number = 0
    @profile.issue_number = 0
    @profile.save!

    redirect_to :back
  end

  protected

  def issue_params
    params.require(:issue).permit(:name, :category_id, :content, :vote_list, :logo)
  end

end

app/controllers/api_v1/issues_controller.rb
class ApiV1::IssuesController < ApiController

before_action :authenticate_user_from_token!, only:[:vote]

  def index
    if authenticate_user_from_token!
      @profile = current_user.profile
      
      @issues = Issue.all
      issue_ids = Issue.includes(:profile_issue_ships).where(:profile_issue_ships => {:profile_id => @profile.id}).pluck(:id)     
      @issues = @issues.select{ |x| !issue_ids.include?(x.id) }

    else 
      @issues = Issue.all
    end
      

  end

  def show
    @issue = Issue.find(params[:issue_id])
    @profile = current_user.profile
    @profile_issue = ProfileIssueShip.where(:profile_id => current_user.profile.id).find_by_issue_id(@issue)
  end

  def vote

    if authenticate_user_from_token!
      @issue = Issue.find(params[:id])    
      @profile = current_user.profile

      my_decision = if params[:votting] == "yes" 
         "1"
        elsif params[:votting] == "no"
          "-1"
        elsif params[:votting] == "pass"
          "0"
        end

      @ship = @profile.profile_issue_ships.where( :issue => @issue ).first_or_initialize
      @ship.decision = my_decision
      @ship.save!

      @profile.update_votes_count!
      @profile.rebuild_profile_legislator_ships!
      
      @similar_legislators = current_user.get_similar_legislators(1)
      @my_decision = current_user.get_issue_decision(@issue) 

      @issues = current_user.get_issues_report
      @issues.each do |i|
        if i[:issue].id.to_s ==params[:id]
          @total_votting = i
        end
      end

      render :json => { :message => "auth_token OK, update OK",
                        :profile_id => @profile.id,
                        :issue_id => @issue.id,
                        :decision => @my_decision,
                        :total_yes => @total_votting[:total_yes],
                        :total_no => @total_votting[:total_no],
                        :total_pass => @total_votting[:total_pass]
                          }, :status => 200   
    else
      render :json => { :message => "auth_token fail"} 
    end
  end

  def clear_vote
    if authenticate_user_from_token!
      @issue = Issue.find(params[:id])
      @profile = current_user.profile
      
      profile_issue = @profile.profile_issue_ships.find_by_issue_id(params[:id])
      if profile_issue
        profile_issue.destroy
        profile_issue.save!
      end

      @profile.update_votes_count!
      @profile.rebuild_profile_legislator_ships!

      @similar_legislators = current_user.get_similar_legislators(1)
      @my_decision = current_user.get_issue_decision(@issue) 

      render :json => { :message => "auth_token OK, delete vote decision OK",
                        :profile_id => @profile.id,
                        :issue_id => @issue.id,
                        :decision => @my_decision
                          }, :status => 200  
    else
      render :json => { :message => "clear_vote auth_token fail"} 
    end



  end

  def clear_all
    if authenticate_user_from_token!
      @profile = current_user.profile

      ProfileLegislatorShip.delete_all
      ProfileIssueShip.delete_all

      @profile.vote_number = 0
      @profile.issue_number = 0
      @profile.save!
      render :json => { :message => "auth_token OK, delete ALL vote decision!",
                        :profile_id => @profile.id,
                        :profile_vote_number => @profile.vote_number,
                          }, :status => 200 
    else
      render :json => { :message => "clear_all auth_token fail"} 
    end

  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @issues = Issue.all
    if current_user
      @profile = current_user.profile
    else

    end
  end

  def show
    @issue = Issue.find(params[:id])
   
    if current_user      
      @my_decision = current_user.get_issue_decision(@issue)      
      @similar_legislators = current_user.get_similar_legislators(1)
      @profile = current_user.profile
    end
  end

  def vote
    @issue = Issue.find(params[:id])    
    @profile = current_user.profile

    my_decision = if params[:votting] == "yes" 
       "1"
      elsif params[:votting] == "no"
        "-1"
      elsif params[:votting] == "pass"
        "0"
      end

    @ship = @profile.profile_issue_ships.where( :issue => @issue ).first_or_initialize
    @ship.decision = my_decision
    @ship.save!

    @profile.update_votes_count!
    @profile.rebuild_profile_legislator_ships!
    
    @similar_legislators = current_user.get_similar_legislators(1)
    @my_decision = current_user.get_issue_decision(@issue) 

    respond_to do |format|
      format.html { redirect_to :back }
      format.js 
    end    
  end

  def clear_vote
    @issue = Issue.find(params[:id])
    @profile = current_user.profile
    
    profile_issue = @profile.profile_issue_ships.find_by_issue_id(params[:id])
    profile_issue.destroy
    profile_issue.save!

    @profile.update_votes_count!
    @profile.rebuild_profile_legislator_ships!

    @similar_legislators = current_user.get_similar_legislators(1)
    @my_decision = current_user.get_issue_decision(@issue) 

    respond_to do |format|
      format.html { redirect_to :back }
      format.js 
    end 

  end

  def clear_all
    @profile = current_user.profile

    current_user.profile.profile_legislator_ships.delete_all
    current_user.profile.profile_issue_ships.delete_all

    @profile.vote_number = 0
    @profile.issue_number = 0
    @profile.save!

    redirect_to :back
  end


  private

  def issue_params
    params.require(:issue).permit()
  end



end

app/helpers/admin/issues_helper.rb
module Admin::IssuesHelper
end

app/helpers/api_v1/issues_helper.rb
module ApiV1::IssuesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper

  def display_personal_decision(decision)
    if decision.nil?
      "你還沒投票喔"
    elsif decision == "1"
      "贊成"
    elsif decision == "-1"
      "反對"
    elsif decision == "0"
      "不表態"
    end
  end

 




end

app/views/issues/_category_icon.html.erb
    <%if i.category.name == "司法/法制" %>
    <td>
      <i class="fa fa-balance-scale"></i>
    </td>

    <% elsif i.category.name == "外交/國防" %>
      <td>
        <i class="fa fa-space-shuttle"></i>
      </td>

    <% elsif i.category.name == "內政"%>
      <td>
        <i class="fa fa-users"></i>
      </td>

    <%elsif i.category.name == "財政"%>
      <td>
        <i class="fa fa-line-chart"></i>
      </td>
      
    <%elsif i.category.name == "經濟"%>
      <td>
        <i class="fa fa-usd"></i>
      </td>
      
    <%elsif i.category.name == "交通"%>
      <td>
        <i class="fa fa-train"></i>
      </td>
      
    <%elsif i.category.name == "教育/文化" %>
      <td>
        <i class="fa fa-university"></i>
      </td>
      
    <%elsif i.category.name == "社福/衛環" %>
      <td>
        <i class="fa fa-wheelchair"></i>
      </td>
    <% end %>

app/views/issues/_similar.html.erb
目前跟你最相像的立委:
<% @similar_legislators.each do |le|%>
  <li>
    <%= le[:legislator].name %>
    <%= le[:score] %>%
  </li> 
<% end %>

app/views/issues/_vote_button.html.erb
<% if current_user && !@profile.vote_issue?(@issue) %>
  

  <div class="col-md-12" id="vote_button">
    <h2>你認為呢？</h2>
    <div class="col-md-4">
      <%= link_to vote_issue_path(@issue, :votting => "yes", :category => @issue.category.english_name), :remote => true, :method => :post do%>
        <div class="vote-yes-button">
        贊成
        </div>
      <%end%>
    </div>
    
    <div class="col-md-4 ">
      <%= link_to vote_issue_path(@issue, :votting => "no", :category => @issue.category.english_name), :remote => true, :method => :post do%>
        <div class="vote-no-button">
        反對
        </div>
      <%end%>

    </div>

    <div class="col-md-4">
      <%= link_to  vote_issue_path(@issue, :votting => "pass", :category => @issue.category.english_name), :remote => true, :method => :post do%>
       <div class="vote-pass-button">
        不表態
        </div>
      <%end%>
    </div>
  </div>

<% elsif current_user && @profile.vote_issue?(@issue)%>  
  <div class="col-md-12" id="vote_button">
    <h2> 
      你的表態：<%=  display_personal_decision(@my_decision) %> 
    </h2>
      <%= link_to  clear_vote_issue_path(@issue, :votting => "re_vote"), :remote => true, :method => :post do%>
        <div class="col-md-4 revote-button">
          後悔了，我想重投
        </div>
      <%end%>
      
    
  </div>

<% else%> 
    <h3>   
      你還沒登入喔！
      <%= link_to "登入投票", user_omniauth_authorize_path(:facebook),:class => "btn btn-primary" %>
    </h3>

<% end %>  

app/views/issues/clear_vote.js.erb
$("#similar-legislater").html('<%= j render :partial=>"similar" %>');
$("#similar-legislater").css("display","none")
$("#vote_button").remove();
$("#re_vote").remove();
$("#vote_declare").append('<%=j render :partial => 'vote_button'%>');

app/views/issues/edit.html.erb
<%= form_for @issue, :url => issue_path(@issue),:method => :patch do |f|%>

<div class="form-group">
  <%= f.label :name, "議題名稱" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :content, "議題內容" %>
  <%= f.text_field :content, :class => "form-control" %>
</div>

<%= f.submit "更新",:class => "btn btn-primary" %>


<% end %>

app/views/issues/index.html.erb
<div class="container col-md-8 col-md-offset-2" id="issue-show">
  <div class="row">
    <% @issues.each do |i| %>
      <% if current_user &&  !@profile.vote_issue?(i)%>
      <%= link_to issue_path(i) do%>
        <div class="col-md-3 not-voted" id="issue_board">
            <h3>
              <%= render :partial => 'category_icon', :locals => { :i => i} %>
              <div>  <%=i.name%></div>
            </h3>
        </div>
      <%end%> 
      <%elsif current_user && @profile.vote_issue?(i)%>
        <%= link_to issue_path(i) do%>
          <div class="col-md-3 voted" id="issue_board">
            <h3>
              <%= render :partial => 'category_icon', :locals => { :i => i} %>
              <div ><%=i.name%></div>
            </h3>
          </div>
        <%end%>
      <%else%>
        <%= link_to issue_path(i) do%>
          <div class="col-md-3 not-voted" id="issue_board">
            <h3>
              <%= render :partial => 'category_icon', :locals => { :i => i} %>
              <div ><%=i.name%></div>
            </h3>
          </div>
        <%end%>
      <%end%>    
    <% end %>
  </div>
</div>

app/views/issues/new.html.erb
<%= form_for @issue, :url => issues_path do |f|%>

<div class="form-group">
  <%= f.label :name, "議題名稱" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :content, "議題內容" %>
  <%= f.text_field :content, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :category_id, "分類" %>
  <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, :class => "form-control" %>
</div>

<%= f.submit "送出",:class => "btn btn-primary" %>


<% end %>

app/views/issues/show.html.erb
<h1 ><%= @issue.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-md-6" >
        
    </div>

  </div>
</div>




<div class="container">
  <div class="row">
    <div class="col-md-5" id="issue_show_photo">
      <%= link_to image_tag(@issue.logo.url(:original))%>
    </div>

    <div class="col-md-7">

      <table class="table" id="issue_show_table">
        <tr>
          <td>
            議題類型： 
            <%= @issue.category.name %>
          </td>
          </td>
        </tr>  
        <tr>
          <td>議題內容： <%= simple_format(@issue.content) %></td>
        </tr>
      </table>

      <div id="vote_declare">
        <%= render :partial => 'vote_button' %>
      </div>
      <% if current_user %>
        <div id="similar-legislater"></div>
      <% end %>
    </div>
  </div>
</div>

<table class="table">
  <tr>
    <td>相關參考法案代碼：<%= @issue.votes.count %></td>
  </tr>
  <tr>
    <td> 
      <% @issue.votes.each do |v| %>
        <li><%= link_to v.uid %> </li> 
      <% end %>
    </td>
  </tr>
</table>

app/views/issues/vote.js.erb
$("#similar-legislater").html('<%= j render :partial=>"similar" %>');
$("#similar-legislater").css("display","block")
$("#vote_button").remove();
$("#re_vote").remove();
$("#vote_declare").append('<%=j render :partial => 'vote_button'%>');