config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "votes#about"
  get "/welcome" => "demos#index"

  resources :legislators

  resources :profiles do
    member do
      get :registed_data
      get :profile_issues_result # get :issues_result
      get :profile_legislators_ships # get :similar_legislators
    end  
  end  

  resources :issues do
    member do
      post :vote
      post :clear_vote
    end
  end

  post "issues/clear_all" => "issues#clear_all"

  resources :votes

  namespace :admin do
    resources :users
    resources :issues 
    resources :votes
    resources :categories
  end  

  post "admin/issues/clear_all" => "admin/issues#clear_all"

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :issues do# ApiV1::IssuesController
      member do
        post :vote
        post :clear_vote
        post :clear_all
      end  
    end

    post "/issue_vote" => "issues#vote"
    get "/issues/show" => "issues#show"
    post "/clear_vote" => "issues#clear_vote"
    post "/clear_all" => "issues#clear_all"

    resources :legislators

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :profiles do
      member do
        get :registed_data
        get :profile_issues_result # get :issues_result
        get :profile_legislators_ships # get :similar_legislators
      end  
    end

    patch "/profile_update" => "profile#update"

  end

  root :to => "issues#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_one :profile

  has_many :issues
  has_many :votes

  serialize :fb_raw_data

  before_create :generate_authentication_token

  def self.get_fb_data(access_token)
    res = RestClient.get "https://graph.facebook.com/v2.4/me",  
    { :params => { :access_token => access_token, :fields =>["id", "name", "email"] } }

    if res.code == 200
      JSON.parse( res.to_str )
    else
      Rails.logger.warn(res.body)
      nil
    end
  end

  def get_issue_decision(issue)
    ship = ProfileIssueShip.where(:profile_id => self.profile.id, :issue_id => issue.id).first
    ship.try(:decision)
  end

  def get_similar_legislators(n=10,county)
    les = Legislator.includes(:profile_legislator_ships).where(:profile_legislator_ships => {:profile_id => self.profile.id})
     
    if county
      les = les.where(:county => county).order("total DESC").limit(n)
    else
      les = les.order("total DESC").limit(n)
    end

     

     my_votes_count = self.profile.vote_number
     
     les.map do |le|
       { 
         :legislator => le,
         :score => ((le.profile_legislator_ships.first.total.to_f / my_votes_count)*100).round(2)
       }
     end
  end

  def get_issues_report
    my_ships = self.profile.profile_issue_ships.includes(:issue => :category)
    issues_ids = my_ships.map{ |s| s.issue_id }
    all_ships = ProfileIssueShip.where( :issue_id => issues_ids )

    my_ships.map do |s|
      {
        :issue => s.issue,
        :category => s.issue.category.name,
        :decision => s.decision,
        :total_yes => all_ships.select{ |a| a.issue_id == s.issue_id && a.decision == "1" }.size,
        :total_no => all_ships.select{ |a| a.issue_id == s.issue_id && a.decision == "-1" }.size,
        :total_pass => all_ships.select{ |a| a.issue_id == s.issue_id && a.decision == "0" }.size,
      }
    end
  end

  def username
    self.profile.username
  end

  def admin?
    self.profile.role == "admin"
  end

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

  def self.from_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      user.fb_raw_data = auth
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.fb_raw_data = auth
      existing_user.save!
      return existing_user
    end


    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.fb_raw_data = auth
    user.save!
    profile = user.create_profile
    profile.username = auth.info.name
    profile.save!
    return user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  #後台登入
  before_action :authenticate_user! 

  #檢查權限
  before_action :check_admin

  layout "admin"

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @issues =  @profile.user.get_issues_report
    
  end

  def edit
    @profile = User.profile.find(params[:id])
  end

  def update
    Profile.find(params[:id]).update(profile_params)
    flash[:notice] = "Update Success!"
    redirect_to admin_users_path   
  end

  private

  def profile_params
    params.require(:profile).permit(:role, :location_id)
  end




end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h1>Admin/User Index</h1>


<h3>User Data</h3>

   


<table class="table">
    <tr>
      <td>姓名</td>
      <td>地點</td> 
      <td>權限</td>
    </tr>
  <% @profiles.each do |p|%>  
    <tr>
      <td><%= link_to p.username, admin_user_path(p) %></td>
      <td><%= p.location.try(:name) %></td>
      <td>
        <%= form_for p, url: admin_user_path(p), :method => :PATCH , :class => "form" do |p|%>

          <div class="form-group">
            <%=p.select :location_id, Location.all.map{ |x| [x.name, x.id]}, :class => "form-control" %>
            <%=p.select :role, [["admin","admin"],["normal","normal"]], :class => "form-control"%>
            <%=p.submit "Update", :class => "btn btn-primary"%>
          </div>
        <%end%>
      </td>
      <td>
        <div class="col-md-6">
          <%= link_to "clear_my_all_vote", admin_issues_clear_all_path(:profile_id => p.id), :method => :post, :class => "btn btn-info btn-large"%>
        </div>
      </td>
    </tr>
  <% end %>

</table>

app/views/admin/users/show.html.erb
<h1> profile_issues_result </h1>
<h2>
Profile ID:<%=@profile.id%>
</h2>
<h2>
Username:<%= @profile.username%>
</h2>
<h2>已經投過的議題：<%= @profile.issue_number%></h2>
<h2>相關法案數：<%= @profile.vote_number%></h2>

<table class="table">
  <tr>
    <td>議題名稱</td>
    <td>議題分類</td> 
    <td>個人投票</td>
    <td>所有投票結果</td>

  </tr>

  <% @issues.each do |i| %> 
  <tr>
    <td><%= link_to i[:issue].name, issue_path(i[:issue]) %></td>
    <td><%= i[:category] %></td>
    <td><%= i[:decision] %></td>
    <td>
    贊成：<%= i[:total_yes] %>
    反對：<%= i[:total_no] %>
    </td>
  </tr>
  <% end %>


</table>