config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "votes#about"
  get "/welcome" => "demos#index"

  resources :legislators

  resources :profiles do
    member do
      get :registed_data
      get :profile_issues_result # get :issues_result
      get :profile_legislators_ships # get :similar_legislators
    end  
  end  

  resources :issues do
    member do
      post :vote
      post :clear_vote
    end
  end

  post "issues/clear_all" => "issues#clear_all"

  resources :votes

  namespace :admin do
    resources :users
    resources :issues 
    resources :votes
    resources :categories
  end  

  post "admin/issues/clear_all" => "admin/issues#clear_all"

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :issues do# ApiV1::IssuesController
      member do
        post :vote
        post :clear_vote
        post :clear_all
      end  
    end

    post "/issue_vote" => "issues#vote"
    get "/issues/show" => "issues#show"
    post "/clear_vote" => "issues#clear_vote"
    post "/clear_all" => "issues#clear_all"

    resources :legislators

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :profiles do
      member do
        get :registed_data
        get :profile_issues_result # get :issues_result
        get :profile_legislators_ships # get :similar_legislators
      end  
    end

    patch "/profile_update" => "profile#update"

  end

  root :to => "issues#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jksong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook),:class => "btn btn-primary" %>
      <% if current_user %>
          <%= current_user.email%>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
      <% end %>

      <h1><%= link_to "政客爽 管理者頁面", admin_users_path %></h1>
        <% if flash[:notice].present? %>
          <div style = "color: green">
            <%= flash[:notice]%>
          </div>
        <% end %>

        <% if flash[:alert].present? %>
          <div style = "color: red">
            <%= flash[:alert]%>
          </div>
        <% end %>
        
        <%= link_to "議題投票", issues_path,:class => "btn btn-default"%>
        <% if current_user %>
          <%= link_to "個人資料", profile_path(current_user) ,:class => "btn btn-default"%>
        <% end %>
        <%= link_to "關於我們", about_path ,:class => "btn btn-default"%>

        <% if current_user && current_user.admin? %>
          <%= link_to "管理者", admin_users_path ,:class => "btn btn-default"%>
        <% end %>

        <hr>

        <%= link_to "管理分類", admin_categories_path,:class => "btn btn-default"%>
        <%= link_to "管理議題", admin_issues_path,:class => "btn btn-default"%>
        <%= link_to "管理法案", admin_votes_path,:class => "btn btn-default"%>
        <%= link_to "管理使用者", admin_users_path,:class => "btn btn-default"%>

<%= yield %>

        <div>  
          <%= link_to "管理議題", admin_issues_path,:class => "btn btn-default"%>
          <%= link_to "管理法案", admin_votes_path,:class => "btn btn-default"%>
          <%= link_to "管理使用者", admin_users_path,:class => "btn btn-default"%>


        </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jksong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top nav2" id="nav1">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div id="jksong_logo">
          <%= link_to image_tag("jksong_logo_3.png"), issues_path %>
        </div>
      </div>
      <div id="navbar" class="navbar-collapse collapse ">
        <div class="container">
          <div class="row">
            <div class="col-md-2"></div>
            <ul class="nav navbar-nav ">
              <li >
                <%= link_to "投票囉！", issues_path%>
              </li>
              <li>
                <% if current_user %>
                  <%= link_to "開票囉！", legislators_path %>
                <% end %>
              </li>
              <% if current_user %>
                <li>
                  <%= link_to "個人專區", profile_path(current_user) %>
                </li>
              <% end %>

              <% if current_user %>
                <li>
                  <%= link_to "關於我們", about_path%>
                </li>
              <% end %>

              <% if current_user && current_user.admin?%>
                <li>
                  <%= link_to "管理者", admin_users_path %>
                </li>
              <% end %>
            </ul>
            <div class="col-md-3 " id="log_in_control_bar">
            <div class="col-md-12">
              <% if current_user %>
                  <%= current_user.profile.username%>
                  <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('登入', new_session_path(:user)) %>
                  
              <% end %>
            </div>
          </div>
         </div>
      </div>
      </div><!--/.nav-collapse -->
    </div>
  </nav>





<div class="header ">
  <div class="container">
    <p>三百年前，鄭克塽領導下，台灣政權投降滿清</p>
    <p>三百年後，台灣在政客爽的領導下會有什麼後果呢？</p>  
    <div id="fB_login_button"> 
      <% if !current_user %>
        <%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook),:class => "btn btn-primary" %>
      <%elsif%>
      
      <%end%>
    </div>  
  </div>
  
</div>

    <div class="clearfix"></div>




    <% if flash[:notice].present? %>
          <div style = "color: green">
            <%= flash[:notice]%>
          </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div style = "color: red">
        <%= flash[:alert]%>
      </div>
    <% end %>


<div class="container  ">
  <%= yield %>
</div>



</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jksong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
</head>
<body>


   
  <%= yield %>




</body>
</html>